### ISSUE TITLE
Problem with template for zabbix 4.0 and 4.2

### ISSUE THREAD

**Issue by myhellone** [allenta/zabbix-template-for-varnish-cache#48]
For zabbix 4.4 work
For zabbix 4.0 and 4.2 I have this error:

`root@lab:~/zabbix-template-for-varnish-cache# /usr/local/bin/jinja2 -D version=4.0 --strict -o template.xml template-app-varnish-cache.j2
Traceback (most recent call last):
  File "/usr/local/bin/jinja2", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jinja2cli/cli.py", line 424, in main
    sys.exit(cli(opts, args))
  File "/usr/local/lib/python2.7/dist-packages/jinja2cli/cli.py", line 314, in cli
    out.write(render(template_path, data, extensions, opts.strict))
  File "/usr/local/lib/python2.7/dist-packages/jinja2cli/cli.py", line 229, in render
    return env.get_template(os.path.basename(template_path)).render(data)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/zabbix-template-for-varnish-cache/template-app-varnish-cache.j2", line 630, in top-level template code
    {{ discovery_rule(
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/root/zabbix-template-for-varnish-cache/template-app-varnish-cache.j2", line 312, in template
    {{ trigger(definition) }}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/root/zabbix-template-for-varnish-cache/template-app-varnish-cache.j2", line 136, in template
    <recovery_mode>{{ trigger_priority('EXPRESSION') }}</recovery_mode>
  File "/usr/local/lib/python2.7/dist-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/root/zabbix-template-for-varnish-cache/template-app-varnish-cache.j2", line 45, in template
    }[name] }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'EXPRESSION'
`

**Comment by carlosabalde** [comment]
Thanks for reporting. The wrong Jinja macro was being called when defining a trigger.
